using System.Net;
using System.Text;
using Ecommerce.Application;
using Microsoft.Playwright;
namespace Ecommerce.Web;
public static class ReportPdf{
 public static async Task<byte[]> CreateAsync(TableVm table){if(table.Rows.Count>2000)throw new BusinessException("Limit PDF reports to 2,000 rows using date filters; use Excel for larger exports.");var html=new StringBuilder("<!doctype html><html><head><meta charset='utf-8'><style>body{font-family:Arial,'Nirmala UI',sans-serif;font-size:10px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #ccc;padding:6px;overflow-wrap:anywhere}th{background:#eee}tr{break-inside:avoid}.section{break-before:page}h2{font-size:14px}</style></head><body><h1>");html.Append(WebUtility.HtmlEncode(table.Title)).Append("</h1>");
 var key=Array.FindIndex(table.Columns,x=>x is "Name" or "Number" or "SKU");if(key<0)key=0;var groups=table.Columns.Length<=8?new[]{Enumerable.Range(0,table.Columns.Length).ToArray()}:Enumerable.Range(0,table.Columns.Length).Where(i=>i!=key).Chunk(6).Select(a=>new[]{key}.Concat(a).ToArray()).ToArray();
 for(int section=0;section<groups.Length;section++){var indexes=groups[section];if(groups.Length>1)html.Append(section==0?"<h2>":"<h2 class='section'>").Append("Field group ").Append(section+1).Append(" of ").Append(groups.Length).Append("</h2>");html.Append("<table><thead><tr>");foreach(var i in indexes)html.Append("<th>").Append(WebUtility.HtmlEncode(table.Columns[i])).Append("</th>");html.Append("</tr></thead><tbody>");foreach(var row in table.Rows){html.Append("<tr>");foreach(var i in indexes)html.Append("<td>").Append(WebUtility.HtmlEncode(row[i])).Append("</td>");html.Append("</tr>");}html.Append("</tbody></table>");}html.Append("</body></html>");try{using var playwright=await Playwright.CreateAsync();await using var browser=await playwright.Chromium.LaunchAsync(new(){Headless=true});var page=await browser.NewPageAsync();await page.SetContentAsync(html.ToString());return await page.PdfAsync(new(){Format="A4",Landscape=table.Columns.Length>6,PrintBackground=true,Margin=new(){Top="12mm",Bottom="12mm",Left="8mm",Right="8mm"}});}catch(PlaywrightException){throw new BusinessException("PDF browser is not installed or could not start. Run scripts/install-pdf.ps1 under the application service account; browser Print / Save PDF is also available.");}}
}
