using System.Security.Claims;
using System.Data;
using Ecommerce.Domain;
using Ecommerce.Application;
using Ecommerce.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Ecommerce.Web.Controllers;
[Route("admin/operations")]
public class OperationsController(AppDb db,OrderService orders,StockService stock,PurchaseService purchase,ReturnService returns,LedgerService ledger):Controller {
 string Actor=>User.FindFirstValue(ClaimTypes.NameIdentifier)!;
 async Task Lookups(){ViewBag.Warehouses=await db.Set<Warehouse>().Where(x=>x.Active).ToListAsync();ViewBag.Skus=await db.Set<ProductSku>().Where(x=>x.Active).ToListAsync();ViewBag.Suppliers=await db.Set<Supplier>().Where(x=>x.Active).ToListAsync();}
 [HttpGet("orders"),Permit("orders.view")]public async Task<IActionResult> Orders(){var dues=new Dictionary<Guid,decimal>();foreach(var o in await db.Set<Order>().Where(x=>x.PaymentMethod=="COD"&&x.PaymentStatus!="Paid").OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync())dues[o.Id]=await orders.CodDueAsync(o);ViewBag.CodDues=dues;ViewBag.Deliveries=await db.Set<Delivery>().Include(x=>x.Order).OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync();ViewBag.Agents=await db.Set<DeliveryAgent>().Where(x=>x.Active).ToListAsync();return View(await db.Set<Order>().Include(x=>x.Lines).OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync());}
 [HttpPost("status"),Permit("orders.edit")]public async Task<IActionResult> Status(Guid id,OrderStatus status){await orders.TransitionAsync(id,status,Actor);return RedirectToAction(nameof(Orders));}
 [HttpPost("collect"),Permit("payments.edit")]public async Task<IActionResult> Collect(Guid id,decimal amount){await orders.CollectCodAsync(id,Actor,amount);return RedirectToAction(nameof(Orders));}
 [HttpGet("inventory"),Permit("inventory.view")]public async Task<IActionResult> Inventory(){await Lookups();ViewBag.Branches=await db.Set<Branch>().Where(x=>x.Active).ToListAsync();ViewBag.Stores=await db.Set<Store>().Include(x=>x.Warehouse).ToListAsync();return View(await db.Set<StockBalance>().Include(x=>x.Sku).Include(x=>x.Warehouse).OrderBy(x=>x.Sku.SKU).ToListAsync());}
 [HttpPost("store"),Permit("inventory.edit")]public async Task<IActionResult> CreateStore(string name,Guid branchId){await new StoreInventoryService(db,ledger).CreateAsync(name,branchId,Actor);return RedirectToAction(nameof(Inventory));}
 [HttpPost("adjust"),Permit("inventory.edit")]public async Task<IActionResult> Adjust(Guid warehouseId,Guid skuId,int quantity,string reason){await stock.AdjustAsync(warehouseId,skuId,quantity,reason,Actor);return RedirectToAction(nameof(Inventory));}
 [HttpPost("transfer"),Permit("inventory.edit")]public async Task<IActionResult> Transfer(Guid from,Guid to,Guid skuId,int quantity){await stock.TransferAsync(from,to,skuId,quantity,Actor);return RedirectToAction(nameof(Inventory));}
 [HttpGet("purchases"),Permit("purchase.view")]public async Task<IActionResult> Purchases(){await Lookups();ViewBag.Invoices=await db.Set<SupplierInvoice>().Include(x=>x.Lines).Include(x=>x.PurchaseOrder).OrderByDescending(x=>x.CreatedAt).Take(200).ToListAsync();return View(await db.Set<PurchaseOrder>().Include(x=>x.Supplier).Include(x=>x.Lines).ThenInclude(x=>x.Sku).OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync());}
 [HttpPost("purchase"),Permit("purchase.create")]public async Task<IActionResult> CreatePurchase(Guid supplierId,Guid warehouseId,Guid[] skuId,int[] quantity,decimal[] cost){await purchase.CreateAsync(supplierId,warehouseId,skuId,quantity,cost,Actor);return RedirectToAction(nameof(Purchases));}
 [HttpPost("approve"),Permit("purchase.approve")]public async Task<IActionResult> Approve(Guid id){await purchase.ApproveAsync(id,Actor);return RedirectToAction(nameof(Purchases));}
 [HttpPost("receive"),Permit("purchase.edit")]public async Task<IActionResult> Receive(Guid id){await purchase.ReceiveAsync(id,Actor);return RedirectToAction(nameof(Purchases));}
 [HttpPost("supplier-invoice"),Permit("purchase.create")]public async Task<IActionResult> Invoice(Guid id,string number,DateTime invoiceDate,DateTime dueDate,Guid[] lineId,int[] quantity){await new SupplierInvoiceService(db,ledger).CreateAsync(id,number,invoiceDate,dueDate,lineId,quantity,Actor);return RedirectToAction(nameof(Purchases));}
 [HttpPost("invoice-approve"),Permit("purchase.approve")]public async Task<IActionResult> InvoiceApprove(Guid id){await new SupplierInvoiceService(db,ledger).ApproveAsync(id,Actor);return RedirectToAction(nameof(Purchases));}
 [HttpPost("invoice-void"),Permit("purchase.approve")]public async Task<IActionResult> InvoiceVoid(Guid id){await new SupplierInvoiceService(db,ledger).VoidAsync(id,Actor);return RedirectToAction(nameof(Purchases));}
 [HttpPost("supplier-payment"),Permit("accounts.edit")]public async Task<IActionResult> SupplierPayment(Guid id,decimal amount){await purchase.PayAsync(id,amount,Actor);return RedirectToAction(nameof(Purchases));}
 [HttpGet("returns"),Permit("returns.view")]public async Task<IActionResult> Returns(){await Lookups();ViewBag.Refunds=await db.Set<PaymentRefund>().Include(x=>x.Order).OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync();return View(await db.Set<ReturnRequest>().Include(x=>x.Order).Include(x=>x.OrderLine).OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync());}
 [HttpPost("replacement"),Permit("returns.approve"),Permit("payments.refund"),Permit("payments.edit")]public async Task<IActionResult> Replacement(Guid id,Guid? targetSkuId,int? targetQuantity,decimal collectedDifference=0,string collectionReference=""){var orderId=await new ReplacementService(db,stock,ledger).CreateAsync(id,Actor,targetSkuId,targetQuantity,collectedDifference,collectionReference);return Redirect("/orders/"+orderId);}
 [HttpPost("delivery-status"),Permit("delivery.edit")]public async Task<IActionResult> DeliveryStatus(Guid id,string status,string note){var allowed=new[]{"Assigned","PickedUp","InTransit","OutForDelivery","Delivered"};var d=await db.Set<Delivery>().Include(x=>x.Order).SingleAsync(x=>x.Id==id);var current=Array.IndexOf(allowed,d.Status);var next=Array.IndexOf(allowed,status);if(next!=current+1||next<1)throw new BusinessException("Choose the next delivery status.");if(status=="Delivered"&&d.Order.Status!=OrderStatus.Delivered)throw new BusinessException("Complete the order delivery workflow first.");d.Status=status;db.Add(new DeliveryHistory{DeliveryId=id,Status=status,Note=note??"",ActorId=Actor});ledger.Audit(Actor,"DeliveryStatus",d,after:status);await db.SaveChangesAsync();return RedirectToAction(nameof(Orders));}
 [HttpPost("inspect"),Permit("returns.approve")]public async Task<IActionResult> Inspect(Guid id,bool accept,bool restock,string note){await returns.InspectAsync(id,accept,restock,note,Actor);return RedirectToAction(nameof(Returns));}
 [HttpPost("refund"),Permit("payments.refund")]public async Task<IActionResult> Refund(Guid id,string externalReference){await returns.RecordRefundAsync(id,externalReference,Actor);return RedirectToAction(nameof(Returns));}
 [HttpPost("delivery"),Permit("delivery.edit")]public async Task<IActionResult> Delivery(Guid orderId,Guid? agentId,string trackingNumber){var o=await db.Set<Order>().FindAsync(orderId);if(o==null)return NotFound();if(o.Status is not (OrderStatus.Packed or OrderStatus.ReadyToShip or OrderStatus.Shipped or OrderStatus.OutForDelivery))throw new BusinessException("Order is not ready for delivery assignment.");var d=await db.Set<Delivery>().FirstOrDefaultAsync(x=>x.OrderId==orderId);if(d==null){d=new Delivery{OrderId=orderId};db.Add(d);}d.DeliveryAgentId=agentId;d.TrackingNumber=trackingNumber??"";db.Add(new OrderHistory{OrderId=orderId,Status=o.Status.ToString(),Note="Courier tracking: "+trackingNumber,ActorId=Actor});ledger.Audit(Actor,"DeliveryAssigned",d);await db.SaveChangesAsync();return RedirectToAction(nameof(Orders));}
 [HttpGet("support"),Permit("support.view")]public async Task<IActionResult> Support(){ViewBag.Reviews=await db.Set<Review>().Include(x=>x.Product).OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync();return View(await db.Set<SupportTicket>().OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync());}
 [HttpPost("support"),Permit("support.edit")]public async Task<IActionResult> Support(Guid id,string status,string response){if(status is not ("Open" or "In Progress" or "Resolved" or "Closed"))return BadRequest();var t=await db.Set<SupportTicket>().SingleAsync(x=>x.Id==id);t.Status=status;t.Response=response??"";if(!string.IsNullOrWhiteSpace(response))db.Add(new SupportReply{SupportTicketId=t.Id,AuthorId=Actor,Staff=true,Message=response});t.AssignedTo=Actor;ledger.Audit(Actor,"SupportUpdated",t);await db.SaveChangesAsync();return RedirectToAction(nameof(Support));}
 [HttpPost("review"),Permit("catalog.edit")]public async Task<IActionResult> Review(Guid id,bool approve){var r=await db.Set<Review>().SingleAsync(x=>x.Id==id);r.Approved=approve;ledger.Audit(Actor,"ReviewModerated",r);await db.SaveChangesAsync();return RedirectToAction(nameof(Support));}
 [HttpGet("accounts"),Permit("accounts.view")]public async Task<IActionResult> Accounts(){ViewBag.Heads=await db.Set<AccountHead>().Where(x=>x.Active).OrderBy(x=>x.Code).ToListAsync();ViewBag.Categories=await db.Set<ExpenseCategory>().Where(x=>x.Active).ToListAsync();ViewBag.Branches=await db.Set<Branch>().Where(x=>x.Active).ToListAsync();ViewBag.Expenses=await db.Set<Expense>().Include(x=>x.ExpenseCategory).OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync();return View(await db.Set<Journal>().Include(x=>x.Lines).ThenInclude(x=>x.AccountHead).OrderByDescending(x=>x.Date).Take(100).ToListAsync());}
 [HttpPost("journal"),Permit("accounts.edit")]public async Task<IActionResult> Journal(string description,string[] code,decimal[] debit,decimal[] credit){if(code.Length!=debit.Length||code.Length!=credit.Length)return BadRequest();var lines=code.Select((c,i)=>(c,debit[i],credit[i],"")).ToArray();await ledger.PostAsync("MAN-"+Guid.NewGuid().ToString("N"),description,lines);await db.SaveChangesAsync();return RedirectToAction(nameof(Accounts));}
 [HttpPost("expense"),Permit("accounts.edit")]public async Task<IActionResult> Expense(Guid categoryId,Guid branchId,string description,decimal amount,string paymentMethod="Cash"){if(paymentMethod is not ("Cash" or "Bank"))throw new BusinessException("Choose Cash or Bank.");if(amount<=0||amount!=CommerceRules.Money(amount))throw new BusinessException("Expense amount must be positive.");var e=new Expense{ExpenseCategoryId=categoryId,BranchId=branchId,Description=description,Amount=amount,PaymentMethod=paymentMethod};db.Add(e);ledger.Audit(Actor,"ExpenseCreated",e);await db.SaveChangesAsync();return RedirectToAction(nameof(Accounts));}
 [HttpPost("expense-pay"),Permit("accounts.approve")]public async Task<IActionResult> ExpensePay(Guid id){await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var e=await db.Set<Expense>().SingleAsync(x=>x.Id==id);if(e.Status=="Paid")return RedirectToAction(nameof(Accounts));await ledger.PostAsync("EXP-"+e.Id,e.Description,("6000",e.Amount,0,""),(e.PaymentMethod=="Bank"?"1010":"1000",0,e.Amount,""));e.Status="Paid";ledger.Audit(Actor,"ExpensePaid",e);await db.SaveChangesAsync();await tx.CommitAsync();return RedirectToAction(nameof(Accounts));}
}
