using System.Globalization;
using System.Text;
using System.IO.Compression;
using System.Xml.Linq;
using Ecommerce.Domain;
using Ecommerce.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Ecommerce.Web.Controllers;
[Route("admin/reports"),Permit("reports.view")]
public class ReportsController(AppDb db,AccessService access):Controller {
 static readonly Dictionary<string,Type> Reports=new(){["supplier-invoices"]=typeof(SupplierInvoice),["supplier-invoice-lines"]=typeof(SupplierInvoiceLine),["fulfilment-allocations"]=typeof(OrderAllocation),["campaign-usage"]=typeof(CampaignUse),["delivery-history"]=typeof(DeliveryHistory),["replacements"]=typeof(Replacement),["sales"]=typeof(Order),["discounts"]=typeof(Order),["vat-tax"]=typeof(Order),["gateway-transactions"]=typeof(PaymentTransaction),["requisitions"]=typeof(PurchaseRequisition),["quotations"]=typeof(SupplierQuotation),["goods-receipts"]=typeof(GoodsReceipt),["supplier-returns"]=typeof(SupplierReturn),["campaigns"]=typeof(Campaign),["payment-reconciliation"]=typeof(PaymentReconciliation),["bank-reconciliation"]=typeof(BankStatementLine),["notifications"]=typeof(OutboxMessage),["search-history"]=typeof(SearchEvent),["products"]=typeof(Product),["categories"]=typeof(Category),["brands"]=typeof(Brand),["variants"]=typeof(ProductSku),["stock"]=typeof(StockBalance),["stock-ledger"]=typeof(StockMovement),["purchases"]=typeof(PurchaseOrder),["suppliers"]=typeof(Supplier),["orders"]=typeof(Order),["payments"]=typeof(PaymentTransaction),["payment-attempts"]=typeof(PaymentAttempt),["refunds"]=typeof(PaymentRefund),["returns"]=typeof(ReturnRequest),["deliveries"]=typeof(Delivery),["coupons"]=typeof(Coupon),["coupon-usage"]=typeof(CouponUse),["expenses"]=typeof(Expense),["audit"]=typeof(AuditEntry),["journals"]=typeof(Journal),["journal-lines"]=typeof(JournalLine),["customers"]=typeof(Address)};
 [HttpGet("")]public IActionResult Index(){ViewBag.Reports=Reports.Keys.Concat(new[]{"trial-balance","profit-loss","balance-sheet","low-stock","inventory-valuation","kpi","cash-book","bank-book","general-ledger","customer-ledger","supplier-ledger","search-analytics","customer-segments"}).ToList();return View();}
 IQueryable<Entity> Query(Type t)=>(IQueryable<Entity>)typeof(DbContext).GetMethod(nameof(DbContext.Set),Type.EmptyTypes)!.MakeGenericMethod(t).Invoke(db,null)!;
 [HttpGet("{name}")]
 public async Task<IActionResult> Show(string name,DateTime? from,DateTime? to,Guid? warehouseId,string? status,string? format,[FromQuery] ReportFilters filters){
  filters.WarehouseId=warehouseId;
  var financial=new[]{"trial-balance","profit-loss","balance-sheet","journals","journal-lines","expenses","bank-reconciliation","cash-book","bank-book","general-ledger","customer-ledger","supplier-ledger"};if(financial.Contains(name)&&!await access.HasAsync(User,"accounts.view"))return Forbid();if(name=="audit"&&!await access.HasAsync(User,"security.manage"))return Forbid();
  if(format!=null&&!await access.HasAsync(User,"reports.export"))return Forbid();var end=to?.Date.AddDays(1);if(name=="balance-sheet")from=null;TableVm table;
  if(name is "cash-book" or "bank-book" or "general-ledger" or "customer-ledger" or "supplier-ledger"){
   if(filters.BranchId.HasValue||filters.WarehouseId.HasValue||filters.CategoryId.HasValue||filters.ProductId.HasValue||filters.OrderStatus!=null||filters.PaymentStatus!=null||filters.PaymentMethod!=null||filters.DeliveryStatus!=null)throw new Ecommerce.Application.BusinessException("Ledger reports support date and party filters only.");
   var q=db.Set<JournalLine>().Include(x=>x.Journal).Include(x=>x.AccountHead).Where(x=>(!from.HasValue||x.Journal.Date>=from)&&(!end.HasValue||x.Journal.Date<end));
   if(name=="cash-book")q=q.Where(x=>x.AccountHead.Code=="1000");if(name=="bank-book")q=q.Where(x=>x.AccountHead.Code=="1010");if(name=="customer-ledger")q=q.Where(x=>x.AccountHead.Code=="1100");if(name=="supplier-ledger")q=q.Where(x=>x.AccountHead.Code=="2000");
   if(!string.IsNullOrWhiteSpace(filters.CustomerId))q=q.Where(x=>x.Party==filters.CustomerId);if(filters.SupplierId.HasValue){var party=filters.SupplierId.ToString();q=q.Where(x=>x.Party==party);}
   var rows=await q.OrderBy(x=>x.Journal.Date).Take(10001).ToListAsync();if(rows.Count>10000)throw new Ecommerce.Application.BusinessException("Narrow dates to fewer than 10,000 rows.");
   table=new(name,["Date","Reference","Account","Party","Description","Debit","Credit"],rows.Select(x=>new[]{x.Journal.Date.ToString("u"),x.Journal.Reference,x.AccountHead.Name,x.Party,x.Journal.Description,x.Debit.ToString("F2"),x.Credit.ToString("F2")}).ToList());
  }else if(name=="search-analytics"){
   var q=db.Set<SearchEvent>().Where(x=>(!from.HasValue||x.CreatedAt>=from)&&(!end.HasValue||x.CreatedAt<end));var rows=await q.GroupBy(x=>x.Query).Select(g=>new{Term=g.Key,Searches=g.Count(),Users=g.Select(x=>x.UserId).Distinct().Count()}).OrderByDescending(x=>x.Searches).Take(1000).ToListAsync();table=new(name,["Search term","Recorded searches","Distinct user identifiers"],rows.Select(x=>new[]{x.Term,x.Searches.ToString(),x.Users.ToString()}).ToList());
  }else if(name=="customer-segments"){
   var rows=await db.Set<Order>().Where(x=>(x.Status==OrderStatus.Delivered||x.Status==OrderStatus.Returned||x.Status==OrderStatus.Refunded)&&(!from.HasValue||x.CreatedAt>=from)&&(!end.HasValue||x.CreatedAt<end)).ToListAsync();table=new(name,["Customer ID","Orders","Delivered total","Last order UTC","Segment"],rows.GroupBy(x=>x.UserId).Select(g=>new[]{g.Key,g.Count().ToString(),g.Sum(x=>x.Total).ToString("F2"),g.Max(x=>x.CreatedAt).ToString("u"),g.Max(x=>x.CreatedAt)<DateTime.UtcNow.AddDays(-90)?"Dormant":g.Count()>1?"Repeat":"New"}).ToList());
  }else if(name is "trial-balance" or "profit-loss" or "balance-sheet"){
   var q=db.Set<JournalLine>().Include(x=>x.AccountHead).Where(x=>(!from.HasValue||x.Journal.Date>=from)&&(!end.HasValue||x.Journal.Date<end));
   var rows=await q.GroupBy(x=>new{x.AccountHead.Code,x.AccountHead.Name,x.AccountHead.Type}).Select(g=>new{g.Key.Code,g.Key.Name,g.Key.Type,Debit=g.Sum(x=>x.Debit),Credit=g.Sum(x=>x.Credit)}).ToListAsync();
   if(name=="profit-loss")rows=rows.Where(x=>x.Type is "Revenue" or "ContraRevenue" or "Expense").ToList();if(name=="balance-sheet")rows=rows.Where(x=>x.Type is "Asset" or "Liability" or "Equity").ToList();
   table=new(name,["Code","Account","Type","Debit","Credit","Debit balance"],rows.Select(x=>new[]{x.Code,x.Name,x.Type,x.Debit.ToString("F2"),x.Credit.ToString("F2"),(x.Debit-x.Credit).ToString("F2")}).ToList());
   if(name=="profit-loss"){var profit=rows.Sum(x=>x.Credit-x.Debit);table.Rows.Add(["","Net profit","", "","",profit.ToString("F2")]);}
   if(name=="balance-sheet"){var earnings=await db.Set<JournalLine>().Where(x=>(!end.HasValue||x.Journal.Date<end)&&(x.AccountHead.Type=="Revenue"||x.AccountHead.Type=="ContraRevenue"||x.AccountHead.Type=="Expense")).SumAsync(x=>(decimal?)(x.Credit-x.Debit))??0;table.Rows.Add(["","Current earnings","Equity","0.00",earnings.ToString("F2"),(-earnings).ToString("F2")]);}
  }else if(name is "low-stock" or "inventory-valuation"){
   var q=filters.Apply(db.Set<StockBalance>(),typeof(StockBalance)).Cast<StockBalance>().Include(x=>x.Sku).Include(x=>x.Warehouse).AsQueryable();if(warehouseId.HasValue)q=q.Where(x=>x.WarehouseId==warehouseId);if(name=="low-stock")q=q.Where(x=>x.OnHand-x.Reserved<=x.Sku.ReorderLevel);var list=await q.Take(10000).ToListAsync();
   table=new(name,["SKU","Warehouse","On hand","Reserved","Available","Moving-average valuation"],list.Select(x=>new[]{x.Sku.SKU,x.Warehouse.Name,x.OnHand.ToString(),x.Reserved.ToString(),(x.OnHand-x.Reserved).ToString(),(x.OnHand*x.AverageCost).ToString("F2")}).ToList());
  }else if(name=="discounts"){
   var orders=await filters.Apply(db.Set<Order>(),typeof(Order)).Cast<Order>().Where(x=>(!from.HasValue||x.CreatedAt>=from)&&(!end.HasValue||x.CreatedAt<end)).OrderByDescending(x=>x.CreatedAt).Take(10001).ToListAsync();if(orders.Count>10000)throw new Ecommerce.Application.BusinessException("Narrow discount report dates.");var ids=orders.Select(x=>x.Id).ToList();var uses=await db.Set<CampaignUse>().Where(x=>ids.Contains(x.OrderId)).ToListAsync();table=new(name,["Order","Status","Coupon discount","Campaign discount","Total discount"],orders.Select(o=>new{o,Campaign=uses.Where(x=>x.OrderId==o.Id).Sum(x=>x.Discount)}).Where(x=>x.o.Discount+x.Campaign>0).Select(x=>new[]{x.o.Number,x.o.Status.ToString(),x.o.Discount.ToString("F2"),x.Campaign.ToString("F2"),(x.o.Discount+x.Campaign).ToString("F2")}).ToList());
  }else if(name=="kpi"){
   var list=await filters.Apply(db.Set<Order>(),typeof(Order)).Cast<Order>().Include(x=>x.Lines).Where(x=>(!from.HasValue||x.CreatedAt>=from)&&(!end.HasValue||x.CreatedAt<end)).ToListAsync();var delivered=list.Where(x=>(x.Status==OrderStatus.Delivered||x.Status==OrderStatus.Returned||x.Status==OrderStatus.Refunded)).ToList();var sales=delivered.Sum(x=>x.Subtotal-x.Discount);var costs=delivered.Sum(x=>x.Lines.Sum(l=>l.Quantity*l.Cost));
   var ids=delivered.Select(x=>x.Id).ToList();var returns=await db.Set<ReturnRequest>().Include(x=>x.OrderLine).Include(x=>x.Order).Where(x=>x.Status=="Accepted"&&ids.Contains(x.OrderId)).ToListAsync();var returnedNet=returns.Sum(x=>Ecommerce.Application.CommerceRules.Money(x.OrderLine.Price*x.Quantity-(x.Order.Subtotal==0?0:x.Order.Discount*x.OrderLine.Price*x.Quantity/x.Order.Subtotal)));var restoredCost=returns.Where(x=>x.Restock).Sum(x=>Ecommerce.Application.CommerceRules.Money(x.OrderLine.Cost*x.Quantity));var buyers=delivered.Select(x=>x.UserId).Distinct().Count();var repeated=delivered.GroupBy(x=>x.UserId).Count(g=>g.Count()>1);
   table=new(name,["Metric","Value"],new List<string[]>{new[]{"Gross delivered product sales",delivered.Sum(x=>x.Subtotal).ToString("F2")},new[]{"Order discounts",delivered.Sum(x=>x.Discount).ToString("F2")},new[]{"Accepted product returns",returnedNet.ToString("F2")},new[]{"Net product sales after returns",(sales-returnedNet).ToString("F2")},new[]{"COGS after restocked returns",(costs-restoredCost).ToString("F2")},new[]{"Gross profit after returns",(sales-returnedNet-costs+restoredCost).ToString("F2")},new[]{"Average delivered order",(delivered.Count==0?0:delivered.Average(x=>x.Total)).ToString("F2")},new[]{"Cancellation rate",(list.Count==0?0:100m*list.Count(x=>x.Status==OrderStatus.Cancelled)/list.Count).ToString("F2")+"%"},new[]{"Accepted return rate by delivered order",(delivered.Count==0?0:100m*returns.Select(x=>x.OrderId).Distinct().Count()/delivered.Count).ToString("F2")+"%"},new[]{"Repeat purchase rate",(buyers==0?0:100m*repeated/buyers).ToString("F2")+"%"},new[]{"Conversion rate","Not measured: visitor/session denominator is not collected"}});
   if(filters.BranchId==null&&filters.WarehouseId==null&&filters.CategoryId==null&&filters.ProductId==null&&string.IsNullOrEmpty(filters.CustomerId)){var ledger=await db.Set<JournalLine>().Include(x=>x.Journal).Include(x=>x.AccountHead).Where(x=>(x.AccountHead.Code=="1200"||x.AccountHead.Code=="5000")&&(!end.HasValue||x.Journal.Date<end)).ToListAsync();var start=from??(ledger.Count==0?DateTime.UtcNow:ledger.Min(x=>x.Journal.Date));var opening=ledger.Where(x=>x.AccountHead.Code=="1200"&&x.Journal.Date<start).Sum(x=>x.Debit-x.Credit);var closing=ledger.Where(x=>x.AccountHead.Code=="1200").Sum(x=>x.Debit-x.Credit);var average=(opening+closing)/2;var cogs=ledger.Where(x=>x.AccountHead.Code=="5000"&&x.Journal.Date>=start).Sum(x=>x.Debit-x.Credit);table.Rows.Add(new[]{"Inventory turnover (period COGS / mean opening and closing book value)",average<=0?"Not available: average inventory value is zero":(cogs/average).ToString("F3")});}else table.Rows.Add(new[]{"Inventory turnover","Available for organization-wide journal scope only"});

  }else{
   if(!Reports.TryGetValue(name,out var t))return NotFound();var q=filters.Apply(Query(t),t);if(name=="sales")q=q.Cast<Order>().Where(x=>(x.Status==OrderStatus.Delivered||x.Status==OrderStatus.Returned||x.Status==OrderStatus.Refunded));if(name=="discounts")q=q.Cast<Order>().Where(x=>x.Discount>0);if(from.HasValue)q=q.Where(x=>x.CreatedAt>=from);if(end.HasValue)q=q.Where(x=>x.CreatedAt<end);if(!string.IsNullOrEmpty(status))q=ReportFilters.WithStatus(q,t,status);var list=await q.OrderByDescending(x=>x.CreatedAt).Take(10001).ToListAsync();if(list.Count>10000)throw new Ecommerce.Application.BusinessException("Narrow the filters to fewer than 10,000 rows.");

   var fields=t.GetProperties().Where(p=>(p.PropertyType.IsValueType||p.PropertyType==typeof(string))&&p.Name is not ("Version" or "Before" or "After")).ToArray();table=new(name,fields.Select(f=>f.Name).ToArray(),list.Select(x=>fields.Select(f=>Convert.ToString(f.GetValue(x),CultureInfo.InvariantCulture)??"").ToArray()).ToList());
  }
  if(format=="csv"){string Safe(string s)=>s.TrimStart().Length>0&&"=+-@".Contains(s.TrimStart()[0])?"'"+s:s;string Line(IEnumerable<string> a)=>string.Join(",",a.Select(x=>"\""+Safe(x).Replace("\"","\"\"")+"\""));var csv=Line(table.Columns)+"\r\n"+string.Join("\r\n",table.Rows.Select(Line));return File(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv)).ToArray(),"text/csv",name+".csv");}
  if(format=="pdf")return File(await ReportPdf.CreateAsync(table),"application/pdf",name+".pdf");
  if(format=="xlsx")return File(ExcelFile(table),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",name+".xlsx");
  return View(table);
 }
 static byte[] ExcelFile(TableVm table){
  using var memory=new MemoryStream();using(var zip=new ZipArchive(memory,ZipArchiveMode.Create,true)){
   void Add(string n,string s){var e=zip.CreateEntry(n);using var writer=new StreamWriter(e.Open(),new UTF8Encoding(false));writer.Write(s);}
   Add("[Content_Types].xml","<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");
   Add("_rels/.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");
   Add("xl/workbook.xml","<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Report\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");
   Add("xl/_rels/workbook.xml.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");
   XNamespace ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";var rows=new[]{table.Columns}.Concat(table.Rows);var doc=new XDocument(new XElement(ns+"worksheet",new XElement(ns+"sheetData",rows.Select(r=>new XElement(ns+"row",r.Select(v=>new XElement(ns+"c",new XAttribute("t","inlineStr"),new XElement(ns+"is",new XElement(ns+"t",v)))))))));Add("xl/worksheets/sheet1.xml",doc.ToString());
  }return memory.ToArray();
 }
}
