using Ecommerce.Domain;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce.Infrastructure;

public sealed record BrandingOptions(string CompanyName,string Address,string Phone,string LogoUrl,string PrimaryColor,string AccentColor,string BackgroundColor,string ReportAddress,string ReportFooter)
{
 public string Email {get;init;}=""; public string Website {get;init;}="";
 public string FaviconUrl {get;init;}=""; public string BannerUrl {get;init;}=""; public string BackgroundImageUrl {get;init;}="";
 public string WhatsAppNumber {get;init;}=""; public string MessengerUrl {get;init;}="";
}

public class BrandingService(AppDb db){
 public static string Color(string value,string fallback)=>System.Text.RegularExpressions.Regex.IsMatch(value,@"^#[0-9a-fA-F]{6}$")?value:fallback;
 public static string SafeUrl(string value)=>value.StartsWith('/')&&!value.StartsWith("//")&&!value.Contains('\\')&&!value.Any(char.IsControl)?value:Uri.TryCreate(value,UriKind.Absolute,out var u)&&u.Scheme=="https"?u.AbsoluteUri:"";
 public static string SafeMessenger(string value)=>Uri.TryCreate(value,UriKind.Absolute,out var u)&&u.Scheme=="https"&&(u.Host=="m.me"||u.Host=="www.messenger.com"||u.Host=="messenger.com")?u.AbsoluteUri:"";
 public async Task<BrandingOptions> GetAsync(){
  var settings=await db.Set<BusinessSetting>().AsNoTracking().Where(x=>x.Active&&x.Group=="Brand").ToDictionaryAsync(x=>x.Name,x=>x.Value);
  var company=await db.Set<Company>().AsNoTracking().Where(x=>x.Active).OrderBy(x=>x.CreatedAt).FirstOrDefaultAsync();
  string S(string key,string fallback)=>settings.TryGetValue(key,out var value)&&!string.IsNullOrWhiteSpace(value)?value:fallback;
  return new BrandingOptions(
   S("CompanyName",S("DisplayName",company?.Name??"Paru Collection")),
   S("CompanyAddress",company?.Address??""),S("CompanyPhone",company?.Phone??""),
   SafeUrl(S("LogoUrl","/images/fallback.svg")),Color(S("PrimaryColor",""),"#153f35"),Color(S("AccentColor",""),"#d7ac67"),Color(S("BackgroundColor",""),"#f7f8f4"),
   S("ReportAddress",company?.Address??""),S("ReportFooter","Generated by E-commerce ERP")) {
   Email=S("CompanyEmail",""), Website=SafeUrl(S("CompanyWebsite","")),
   FaviconUrl=SafeUrl(S("FaviconUrl","")), BannerUrl=SafeUrl(S("BannerUrl","")), BackgroundImageUrl=SafeUrl(S("BackgroundImageUrl","")),
   WhatsAppNumber=System.Text.RegularExpressions.Regex.IsMatch(S("WhatsAppNumber",""), @"^[1-9][0-9]{7,14}$")?S("WhatsAppNumber",""):"",
   MessengerUrl=SafeMessenger(S("MessengerUrl",""))
  };
 }
}
