using System.Data;
using Ecommerce.Application;
using Ecommerce.Domain;
using Microsoft.EntityFrameworkCore;
namespace Ecommerce.Infrastructure;
public class ProcurementService(AppDb db,StockService stock,LedgerService ledger){
 public async Task<Guid> RequestAsync(Guid warehouse,string purpose,Guid[] skus,int[] quantities,string actor){
  if(skus.Length==0||skus.Length!=quantities.Length||skus.Distinct().Count()!=skus.Length)throw new BusinessException("Enter distinct requisition lines.");
  var r=new PurchaseRequisition{Number="REQ-"+Guid.NewGuid().ToString("N")[..12],WarehouseId=warehouse,RequestedBy=actor,Purpose=purpose};for(int i=0;i<skus.Length;i++){CommerceRules.Quantity(quantities[i]);r.Lines.Add(new RequisitionLine{SkuId=skus[i],Quantity=quantities[i]});}db.Add(r);ledger.Audit(actor,"RequisitionCreated",r);await db.SaveChangesAsync();return r.Id;
 }
 public async Task ApproveAsync(Guid id,string actor){var r=await db.Set<PurchaseRequisition>().SingleAsync(x=>x.Id==id);if(r.Status!="Draft")throw new BusinessException("Requisition is not a draft.");r.Status="Approved";ledger.Audit(actor,"RequisitionApproved",r);await db.SaveChangesAsync();}
 public async Task QuoteAsync(Guid request,Guid supplier,DateTime until,string reference,Guid[] lineIds,decimal[] costs,string actor){
  var r=await db.Set<PurchaseRequisition>().Include(x=>x.Lines).SingleAsync(x=>x.Id==request);if(r.Status!="Approved"||until.Date<DateTime.UtcNow.Date||lineIds.Length!=r.Lines.Count||costs.Length!=lineIds.Length||lineIds.Distinct().Count()!=lineIds.Length)throw new BusinessException("Quotation must cover every line of an approved requisition and remain valid.");
  var q=new SupplierQuotation{PurchaseRequisitionId=request,SupplierId=supplier,ValidUntil=until.Date.AddDays(1),Reference=reference};for(int i=0;i<lineIds.Length;i++){var l=r.Lines.SingleOrDefault(x=>x.Id==lineIds[i])??throw new BusinessException("Unknown requisition line.");if(costs[i]<0||costs[i]!=CommerceRules.Money(costs[i]))throw new BusinessException("Invalid cost.");q.Lines.Add(new QuotationLine{SkuId=l.SkuId,Quantity=l.Quantity,UnitCost=costs[i]});}q.Total=q.Lines.Sum(x=>x.Quantity*x.UnitCost);db.Add(q);ledger.Audit(actor,"QuotationCreated",q);await db.SaveChangesAsync();
 }
 public async Task<Guid> AwardAsync(Guid id,string actor){await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var q=await db.Set<SupplierQuotation>().Include(x=>x.Lines).Include(x=>x.PurchaseRequisition).SingleAsync(x=>x.Id==id);if(q.Status!="Submitted"||q.PurchaseRequisition.Status!="Approved"||q.ValidUntil<DateTime.UtcNow)throw new BusinessException("Quotation cannot be awarded.");var p=new PurchaseOrder{Number="PO-"+Guid.NewGuid().ToString("N")[..12],SupplierId=q.SupplierId,WarehouseId=q.PurchaseRequisition.WarehouseId,Total=q.Total};foreach(var l in q.Lines)p.Lines.Add(new PurchaseLine{SkuId=l.SkuId,Quantity=l.Quantity,UnitCost=l.UnitCost});q.Status="Awarded";q.PurchaseRequisition.Status="Awarded";db.Add(p);ledger.Audit(actor,"QuotationAwarded",q,after:p.Number);await db.SaveChangesAsync();await tx.CommitAsync();return p.Id;}
 public async Task ReceiveAsync(Guid purchaseId,Guid[] lineIds,int[] quantities,string reference,string actor){
  if(string.IsNullOrWhiteSpace(reference)||lineIds.Length!=quantities.Length||lineIds.Distinct().Count()!=lineIds.Length)throw new BusinessException("Receipt reference and distinct lines are required.");
  await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var previous=await db.Set<GoodsReceipt>().SingleOrDefaultAsync(x=>x.Reference==reference);if(previous!=null){if(previous.PurchaseOrderId!=purchaseId)throw new BusinessException("Receipt reference already belongs to another purchase.");return;}
  var p=await db.Set<PurchaseOrder>().Include(x=>x.Lines).SingleAsync(x=>x.Id==purchaseId);if(p.Status is not ("Approved" or "PartReceived"))throw new BusinessException("Purchase is not receivable.");var receipt=new GoodsReceipt{PurchaseOrderId=p.Id,Reference=reference,ActorId=actor};decimal total=0;
  for(int i=0;i<lineIds.Length;i++){if(quantities[i]==0)continue;CommerceRules.Quantity(quantities[i]);var l=p.Lines.SingleOrDefault(x=>x.Id==lineIds[i])??throw new BusinessException("Unknown purchase line.");if(l.ReceivedQuantity+quantities[i]>l.Quantity)throw new BusinessException("Receipt exceeds ordered quantity.");l.ReceivedQuantity+=quantities[i];receipt.Lines.Add(new GoodsReceiptLine{PurchaseLineId=l.Id,Quantity=quantities[i],UnitCost=l.UnitCost});await stock.ChangeAsync(p.WarehouseId,l.SkuId,quantities[i],0,"GoodsReceipt",reference,actor,l.UnitCost);total+=quantities[i]*l.UnitCost;}
  if(receipt.Lines.Count==0)throw new BusinessException("Enter at least one receipt quantity.");p.ReceivedTotal+=total;p.Status=p.Lines.All(x=>x.ReceivedQuantity==x.Quantity)?"Received":"PartReceived";db.Add(receipt);if(total>0)await ledger.PostAsync("GRN-"+reference,"Goods receipt",("1200",total,0,""),("2000",0,total,p.SupplierId.ToString()));ledger.Audit(actor,"GoodsReceived",receipt);await db.SaveChangesAsync();await tx.CommitAsync();
 }
 public async Task ReturnAsync(Guid lineId,int quantity,string reference,string reason,string actor){
  CommerceRules.Quantity(quantity);if(string.IsNullOrWhiteSpace(reference)||string.IsNullOrWhiteSpace(reason))throw new BusinessException("Reference and reason required.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var prior=await db.Set<SupplierReturn>().SingleOrDefaultAsync(x=>x.Reference==reference);if(prior!=null){if(prior.PurchaseLineId!=lineId)throw new BusinessException("Return reference already used.");return;}
  var l=await db.Set<PurchaseLine>().Include(x=>x.PurchaseOrder).SingleAsync(x=>x.Id==lineId);var p=l.PurchaseOrder;if(quantity>l.ReceivedQuantity-l.ReturnedQuantity)throw new BusinessException("Return exceeds received quantity.");var balance=await db.Set<StockBalance>().SingleAsync(x=>x.SkuId==l.SkuId&&x.WarehouseId==p.WarehouseId);var removed=CommerceRules.Money(balance.AverageCost*quantity);var credit=CommerceRules.Money(l.UnitCost*quantity);await stock.ChangeAsync(p.WarehouseId,l.SkuId,-quantity,0,"PurchaseReturn",reference,actor);l.ReturnedQuantity+=quantity;p.ReturnedTotal+=credit;
  var lines=new List<(string,decimal,decimal,string)>{("2000",credit,0,p.SupplierId.ToString()),("1200",0,removed,"")};var variance=removed-credit;if(variance>0)lines.Add(("5000",variance,0,""));if(variance<0)lines.Add(("5000",0,-variance,""));if(removed>0||credit>0)await ledger.PostAsync("PRET-"+reference,"Supplier return",lines.ToArray());var ret=new SupplierReturn{PurchaseLineId=lineId,Quantity=quantity,Reference=reference,Reason=reason,Amount=credit,ActorId=actor};db.Add(ret);ledger.Audit(actor,"SupplierReturn",ret);await db.SaveChangesAsync();await tx.CommitAsync();
 }
}
