using System.Data;
using Ecommerce.Application;
using Ecommerce.Domain;
using Microsoft.EntityFrameworkCore;
namespace Ecommerce.Infrastructure;
public class ReconciliationService(AppDb db,LedgerService ledger){
 public async Task PaymentAsync(Guid id,decimal amount,string reference,string actor){if(amount<0||string.IsNullOrWhiteSpace(reference))throw new BusinessException("Amount and external reference required.");var p=await db.Set<PaymentTransaction>().SingleAsync(x=>x.Id==id);var row=new PaymentReconciliation{PaymentTransactionId=id,ExternalAmount=amount,ExternalReference=reference,Status=p.Status=="Paid"&&p.Amount==amount?"Matched":"Mismatch",ActorId=actor};db.Add(row);ledger.Audit(actor,"PaymentReconciled",row);await db.SaveChangesAsync();}
 public async Task BankAsync(string reference,DateTime date,decimal amount,Guid? lineId,string actor){if(string.IsNullOrWhiteSpace(reference)||amount==0||amount!=CommerceRules.Money(amount))throw new BusinessException("Valid reference and nonzero two-decimal signed amount required.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);if(lineId.HasValue){var line=await db.Set<JournalLine>().Include(x=>x.AccountHead).SingleAsync(x=>x.Id==lineId);if(line.AccountHead.Code is not ("1000" or "1010")||line.Debit-line.Credit!=amount||await db.Set<BankStatementLine>().AnyAsync(x=>x.JournalLineId==lineId))throw new BusinessException("Cash/bank journal amount mismatch or already matched.");}var row=new BankStatementLine{Reference=reference,Date=date,Amount=amount,JournalLineId=lineId,Status=lineId.HasValue?"Matched":"Unmatched"};db.Add(row);ledger.Audit(actor,"BankReconciled",row);await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task VoucherAsync(string type,string party,decimal amount,string account,string description,string actor){if(amount<=0||amount!=CommerceRules.Money(amount))throw new BusinessException("Invalid amount.");(string,decimal,decimal,string)[] lines=type switch{"Receipt"=>[("1000",amount,0,""),(account,0,amount,party)],"Payment"=>[(account,amount,0,party),("1000",0,amount,"")],"Contra"=>[("1010",amount,0,""),("1000",0,amount,"")],_=>throw new BusinessException("Invalid voucher type.")};await ledger.PostAsync(type+"-"+Guid.NewGuid().ToString("N"),description,lines);await db.SaveChangesAsync();}
}
