using System.Data;
using System.Globalization;
using System.Text.Json;
using Ecommerce.Domain;
using Ecommerce.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
namespace Ecommerce.Infrastructure;
public class RefundGatewayService(HttpClient http,AppDb db,IConfiguration config,ReturnService returns,LedgerService ledger){
 string Root=>config.GetValue<bool>("Payments:SSLCommerz:Sandbox")?"https://sandbox.sslcommerz.com":"https://securepay.sslcommerz.com";
 async Task<JsonDocument> Call(Dictionary<string,string> values,CancellationToken ct){if(!config.GetValue<bool>("Payments:SSLCommerz:RefundEnabled"))throw new BusinessException("Enable SSLCommerz refunds only after merchant sandbox validation.");values["store_id"]=config["Payments:SSLCommerz:StoreId"]??"";values["store_passwd"]=config["Payments:SSLCommerz:StorePassword"]??"";values["format"]="json";if(values["store_id"]==""||values["store_passwd"]=="")throw new BusinessException("Merchant credentials missing.");var url=Root+"/validator/api/merchantTransIDvalidationAPI.php?"+string.Join("&",values.Select(x=>Uri.EscapeDataString(x.Key)+"="+Uri.EscapeDataString(x.Value)));using var response=await http.GetAsync(url,ct);response.EnsureSuccessStatusCode();return JsonDocument.Parse(await response.Content.ReadAsStringAsync(ct));}
 static string Field(JsonElement e,string key)=>e.TryGetProperty(key,out var p)?p.ToString():"";
 public async Task StartAsync(Guid id,string actor,CancellationToken ct){
  if(!config.GetValue<bool>("Payments:SSLCommerz:RefundEnabled"))throw new BusinessException("Online refund execution is disabled.");
  PaymentRefund refund;PaymentTransaction payment;
  await using(var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct)){
   refund=await db.Set<PaymentRefund>().SingleAsync(x=>x.Id==id,ct);if(refund.Status!="Requested")throw new BusinessException("Refund was already submitted; query or reconcile its status instead of resending.");payment=await db.Set<PaymentTransaction>().SingleOrDefaultAsync(x=>x.OrderId==refund.OrderId&&x.Gateway=="SSLCommerz"&&x.Status=="Paid",ct)??throw new BusinessException("Verified SSLCommerz payment required.");var other=(await db.Set<PaymentRefund>().Where(x=>x.OrderId==refund.OrderId&&x.Id!=id&&x.Status!="Rejected").Select(x=>x.Amount).ToListAsync(ct)).Sum();if(refund.Amount<=0||refund.Amount+other>payment.Amount)throw new BusinessException("Refund requests exceed the collected amount.");refund.Status="Initiating";ledger.Audit(actor,"GatewayRefundInitiating",refund);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);
  }
  try{using var result=await Call(new(){["bank_tran_id"]=payment.GatewayTransactionId,["refund_trans_id"]=refund.Id.ToString("N"),["refe_id"]=refund.Id.ToString("N"),["refund_amount"]=refund.Amount.ToString("F2",CultureInfo.InvariantCulture),["refund_remarks"]=refund.Reason,["v"]="1"},ct);var e=result.RootElement;var reference=Field(e,"refund_ref_id");if(Field(e,"APIConnect")!="DONE"||Field(e,"bank_tran_id")!=payment.GatewayTransactionId||Field(e,"trans_id")!=payment.TransactionId||reference==""||Field(e,"status") is not ("success" or "processing"))throw new BusinessException("Gateway response needs manual reconciliation.");refund.ExternalReference=reference;refund.Status="Processing";await db.SaveChangesAsync(ct);}catch{refund.Status="Uncertain";await db.SaveChangesAsync(CancellationToken.None);throw new BusinessException("Refund submission could not be confirmed. Reconcile in the merchant portal; do not submit it again.");}
 }
 public async Task QueryAsync(Guid id,string actor,CancellationToken ct){var r=await db.Set<PaymentRefund>().SingleAsync(x=>x.Id==id,ct);if(r.Status=="Completed")return;if(r.Status!="Processing"||string.IsNullOrWhiteSpace(r.ExternalReference))throw new BusinessException("A recorded gateway refund reference is required.");var payment=await db.Set<PaymentTransaction>().SingleAsync(x=>x.OrderId==r.OrderId&&x.Gateway=="SSLCommerz"&&x.Status=="Paid",ct);using var result=await Call(new(){["refund_ref_id"]=r.ExternalReference},ct);var e=result.RootElement;if(Field(e,"APIConnect")!="DONE"||Field(e,"bank_tran_id")!=payment.GatewayTransactionId||Field(e,"tran_id")!=payment.TransactionId||Field(e,"refund_ref_id")!=r.ExternalReference)throw new BusinessException("Refund verification mismatch.");if(Field(e,"status")=="refunded")await returns.RecordRefundAsync(id,r.ExternalReference,actor);else if(Field(e,"status")=="cancelled"){r.Status="GatewayCancelled";await db.SaveChangesAsync(ct);}else if(Field(e,"status")!="processing")throw new BusinessException("Unknown gateway refund status.");}
}
