using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Ecommerce.Domain;
using Ecommerce.Application;
using Ecommerce.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Xunit;
namespace Ecommerce.IntegrationTests;
public class LiveEnvironmentTests{
 [ExternalFact("ERP_SQL_TEST_CONNECTION")]public async Task SqlServerMigrationAndRowversion(){var connection=Environment.GetEnvironmentVariable("ERP_SQL_TEST_CONNECTION")!;var cs=new Microsoft.Data.SqlClient.SqlConnectionStringBuilder(connection);Assert.StartsWith("Paru_Acceptance_",cs.InitialCatalog);var options=new DbContextOptionsBuilder<AppDb>().UseSqlServer(connection).Options;await using var db=new AppDb(options);await db.Database.MigrateAsync();await db.Database.MigrateAsync();Assert.False(db.Database.HasPendingModelChanges());var category=new Category{Name="Rowversion test",Slug="rowversion-"+Guid.NewGuid().ToString("N")};db.Add(category);await db.SaveChangesAsync();Assert.NotEmpty(category.Version);await using var stale=new AppDb(options);var copy=await stale.Set<Category>().SingleAsync(x=>x.Id==category.Id);category.Name="Updated concurrently";await db.SaveChangesAsync();copy.Name="Stale update";await Assert.ThrowsAsync<DbUpdateConcurrencyException>(()=>stale.SaveChangesAsync());}

 [ExternalFact("ERP_SQL_TEST_CONNECTION")]public async Task SqlServerConcurrentCheckoutDoesNotOversell(){var cs=new Microsoft.Data.SqlClient.SqlConnectionStringBuilder(Environment.GetEnvironmentVariable("ERP_SQL_TEST_CONNECTION")!);Assert.StartsWith("Paru_Acceptance_",cs.InitialCatalog);cs.InitialCatalog+="_Workflow";var options=new DbContextOptionsBuilder<AppDb>().UseSqlServer(cs.ConnectionString).Options;await using var db=new AppDb(options);await db.Database.MigrateAsync();var company=new Company{Name="Concurrency test"};var branch=new Branch{Name="Test",CompanyId=company.Id};var warehouse=new Warehouse{Name="Test",BranchId=branch.Id};var category=new Category{Name="Test",Slug=Guid.NewGuid().ToString("N")};var product=new Product{Name="Last unit",Code=Guid.NewGuid().ToString("N"),Slug=Guid.NewGuid().ToString("N"),CategoryId=category.Id};var sku=new ProductSku{Name="Only",SKU=Guid.NewGuid().ToString("N"),ProductId=product.Id,SalePrice=100};var zone=new DeliveryZone{Name="Test",Charge=0};db.AddRange(company,branch,warehouse,category,product,sku,zone,new StockBalance{WarehouseId=warehouse.Id,SkuId=sku.Id,OnHand=1});var uid1=Guid.NewGuid().ToString();var uid2=Guid.NewGuid().ToString();db.AddRange(new CartItem{Owner=uid1,SkuId=sku.Id,Quantity=1},new CartItem{Owner=uid2,SkuId=sku.Id,Quantity=1});await db.SaveChangesAsync();
  async Task<bool> TryCheckout(string uid){await using var context=new AppDb(options);var ledger=new LedgerService(context);var service=new OrderService(context,new StockService(context,ledger),ledger);try{await service.CheckoutAsync(new CheckoutRequest(uid,"Buyer","01000000000","test@example.com","Test",zone.Id,warehouse.Id,"","COD",Guid.NewGuid().ToString()));return true;}catch(BusinessException){return false;}catch(Microsoft.Data.SqlClient.SqlException ex) when(ex.Number==1205){return false;}catch(DbUpdateException ex) when(ex.InnerException is Microsoft.Data.SqlClient.SqlException sql&&sql.Number==1205){return false;}}
  var outcomes=await Task.WhenAll(TryCheckout(uid1),TryCheckout(uid2));Assert.Single(outcomes,x=>x);db.ChangeTracker.Clear();var stock=await db.Set<StockBalance>().SingleAsync(x=>x.SkuId==sku.Id);Assert.Equal(1,stock.OnHand);Assert.Equal(1,stock.Reserved);Assert.Equal(1,await db.Set<OrderLine>().CountAsync(x=>x.SkuId==sku.Id));
 }
 [ExternalFact("ERP_SQL_TEST_CONNECTION")]public async Task SqlServerUpgradePreservesExistingCampaign(){var cs=new Microsoft.Data.SqlClient.SqlConnectionStringBuilder(Environment.GetEnvironmentVariable("ERP_SQL_TEST_CONNECTION")!);Assert.StartsWith("Paru_Acceptance_",cs.InitialCatalog);cs.InitialCatalog+="_Upgrade_"+Guid.NewGuid().ToString("N")[..8];await using var db=new AppDb(new DbContextOptionsBuilder<AppDb>().UseSqlServer(cs.ConnectionString).Options);try{await db.GetService<IMigrator>().MigrateAsync("20261001011000_OperationalSettings");var id=Guid.NewGuid();var start=DateTime.UtcNow.AddDays(-1);var end=DateTime.UtcNow.AddDays(1);await db.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO [Campaign] ([Id],[Name],[Active],[Percent],[StartsAt],[EndsAt],[CustomerId],[CreatedBy],[UpdatedBy],[CreatedAt]) VALUES ({id},N'Existing',1,20,{start},{end},N'',N'system',N'system',{start})");await db.Database.MigrateAsync();var c=await db.Set<Campaign>().SingleAsync(x=>x.Id==id);Assert.Equal(20,c.Percent);Assert.Equal(999999999,c.MaximumDiscount);Assert.Equal(int.MaxValue,c.UsageLimit);Assert.Equal(int.MaxValue,c.PerCustomerLimit);Assert.False(db.Database.HasPendingModelChanges());}finally{await db.Database.EnsureDeletedAsync();}}
 [ExternalFact("ERP_OLLAMA_TEST_MODEL")]public async Task RealOllamaAnswersAuthorizedFacts(){await using var c=new Microsoft.Data.Sqlite.SqliteConnection("Data Source=:memory:");await c.OpenAsync();await using var db=new TestDb(new DbContextOptionsBuilder<AppDb>().UseSqlite(c).Options);await db.Database.EnsureCreatedAsync();var category=new Category{Name="Test",Slug="test"};var product=new Product{Name="Blue mug",Code="MUG",Slug="blue-mug",CategoryId=category.Id};db.AddRange(category,product,new ProductSku{ProductId=product.Id,Name="Blue",SKU="MUG-BLUE",SalePrice=125});await db.SaveChangesAsync();var config=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{["Ollama:Model"]=Environment.GetEnvironmentVariable("ERP_OLLAMA_TEST_MODEL")}).Build();using var http=new HttpClient(new HttpClientHandler{UseProxy=false}){BaseAddress=new Uri(Environment.GetEnvironmentVariable("ERP_OLLAMA_TEST_URL")??"http://127.0.0.1:11434/"),Timeout=TimeSpan.FromSeconds(120)};var answer=await new OllamaService(http,db,config).AskAsync("What is the price of Blue mug? Answer in one short English sentence using the product price.","test-customer",false,default);Assert.Contains("125",answer);Assert.DoesNotContain("<script",answer,StringComparison.OrdinalIgnoreCase);}
}
public class ExternalFactAttribute:FactAttribute{public ExternalFactAttribute(string variable){if(string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable(variable)))Skip="Set "+variable+" for the dedicated external acceptance environment.";}}
