using Microsoft.Extensions.Configuration;
using System.Security.Claims;
using Ecommerce.Application;
using Ecommerce.Domain;
using Ecommerce.Infrastructure;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Xunit;
namespace Ecommerce.IntegrationTests;
public class TestDb(DbContextOptions<AppDb> options):AppDb(options){public override Task<int> SaveChangesAsync(CancellationToken ct=default){foreach(var entry in ChangeTracker.Entries<Entity>().Where(x=>x.State==EntityState.Added||x.State==EntityState.Modified))entry.Entity.Version=Guid.NewGuid().ToByteArray();return base.SaveChangesAsync(ct);}protected override void OnModelCreating(ModelBuilder b){base.OnModelCreating(b);foreach(var e in b.Model.GetEntityTypes()){var p=e.FindProperty("Version");if(p!=null)p.ValueGenerated=ValueGenerated.Never;}}}
public sealed class WorkflowTests:IAsyncLifetime {
 readonly SqliteConnection connection=new("Data Source=:memory:");AppDb db=null!;LedgerService ledger=null!;StockService stock=null!;OrderService orders=null!;Guid wh,sku,zone,supplier;
 public async Task InitializeAsync(){var sql=Environment.GetEnvironmentVariable("ERP_SQL_TEST_CONNECTION");if(sql==null){await connection.OpenAsync();db=new TestDb(new DbContextOptionsBuilder<AppDb>().UseSqlite(connection).Options);await db.Database.EnsureCreatedAsync();}else{var cs=new Microsoft.Data.SqlClient.SqlConnectionStringBuilder(sql);if(!cs.InitialCatalog.StartsWith("Paru_Acceptance_"))throw new InvalidOperationException("Dedicated acceptance database required.");cs.InitialCatalog+="_Case_"+Guid.NewGuid().ToString("N")[..10];db=new AppDb(new DbContextOptionsBuilder<AppDb>().UseSqlServer(cs.ConnectionString).Options);await db.Database.MigrateAsync();}ledger=new LedgerService(db);stock=new StockService(db,ledger);orders=new OrderService(db,stock,ledger);
  var co=new Company{Name="Test"};var branch=new Branch{Name="Main",CompanyId=co.Id};var w=new Warehouse{Name="Warehouse",BranchId=branch.Id};var cat=new Category{Name="Test",Slug="test"};var p=new Product{Name="Test Product",Code="TEST",Slug="test-product",CategoryId=cat.Id};var s=new ProductSku{ProductId=p.Id,Name="M",SKU="TEST-M",SalePrice=100,PurchasePrice=60};var z=new DeliveryZone{Name="Local",Charge=10};var sup=new Supplier{Name="Supplier"};db.AddRange(co,branch,w,cat,p,s,z,sup);wh=w.Id;sku=s.Id;zone=z.Id;supplier=sup.Id;
  foreach(var code in new[]{"1000","1010","1100","1200","2000","2100","3100","4000","4100","4200","5000","6000"})db.Add(new AccountHead{Code=code,Name=code});db.Add(new StockBalance{WarehouseId=wh,SkuId=sku,OnHand=10,AverageCost=60});await db.SaveChangesAsync();
 }
 public async Task DisposeAsync(){if(db.Database.IsSqlServer())await db.Database.EnsureDeletedAsync();await db.DisposeAsync();await connection.DisposeAsync();}
 CheckoutRequest Request(string key)=>new("customer","Test Buyer","01000000000","test@example.com","Test address",zone,wh,"","COD",key);
 async Task<Order> Checkout(int qty=2){await new CartService(db).SetAsync("customer",sku,qty);return await orders.CheckoutAsync(Request(Guid.NewGuid().ToString()));}
 [Fact]public async Task CheckoutUsesDatabasePriceAndReservesStock(){var o=await Checkout();Assert.Equal(210m,o.Total);Assert.Equal(2,(await db.Set<StockBalance>().SingleAsync()).Reserved);Assert.Empty(await db.Set<CartItem>().ToListAsync());}
 [Fact]public async Task DuplicateCheckoutReturnsSameOrder(){var key=Guid.NewGuid().ToString();await new CartService(db).SetAsync("customer",sku,1);var first=await orders.CheckoutAsync(Request(key));var second=await orders.CheckoutAsync(Request(key));Assert.Equal(first.Id,second.Id);Assert.Equal(1,await db.Set<Order>().CountAsync());}
 [Fact]public async Task OversellingRollsBack(){await new CartService(db).SetAsync("customer",sku,11);await Assert.ThrowsAsync<BusinessException>(()=>orders.CheckoutAsync(Request(Guid.NewGuid().ToString())));db.ChangeTracker.Clear();Assert.Equal(0,await db.Set<Order>().CountAsync());Assert.Equal(0,(await db.Set<StockBalance>().SingleAsync()).Reserved);}
 [Fact]public async Task CancelReleasesReservation(){var o=await Checkout();await orders.TransitionAsync(o.Id,OrderStatus.Cancelled,"admin");Assert.Equal(0,(await db.Set<StockBalance>().SingleAsync()).Reserved);Assert.Equal(10,(await db.Set<StockBalance>().SingleAsync()).OnHand);}
 [Fact]public async Task ShipmentIssuesReservedStockOnce(){var o=await Checkout();foreach(var s in new[]{OrderStatus.Confirmed,OrderStatus.Processing,OrderStatus.Packed,OrderStatus.ReadyToShip,OrderStatus.Shipped})await orders.TransitionAsync(o.Id,s,"admin");await orders.TransitionAsync(o.Id,OrderStatus.Shipped,"admin");var balance=await db.Set<StockBalance>().SingleAsync();Assert.Equal(8,balance.OnHand);Assert.Equal(0,balance.Reserved);}
 [Fact]public async Task PurchaseReceiveIsIdempotent(){var service=new PurchaseService(db,stock,ledger);var p=await service.CreateAsync(supplier,wh,[sku],[4],[50m],"admin");await service.ApproveAsync(p.Id,"admin");await service.ReceiveAsync(p.Id,"admin");await service.ReceiveAsync(p.Id,"admin");Assert.Equal(14,(await db.Set<StockBalance>().SingleAsync()).OnHand);Assert.Equal(57.1429m,(await db.Set<StockBalance>().SingleAsync()).AverageCost);Assert.Equal(1,await db.Set<Journal>().CountAsync());}
 [Fact]public async Task UserDenyOverridesRoleAllow(){db.AddRange(new PermissionGrant{Role="Manager",Permission="orders.view"},new PermissionGrant{UserId="staff",Permission="orders.view",Allowed=false});await db.SaveChangesAsync();var principal=new ClaimsPrincipal(new ClaimsIdentity(new[]{new Claim(ClaimTypes.NameIdentifier,"staff"),new Claim(ClaimTypes.Role,"Manager")},"Test"));Assert.False(await new AccessService(db).HasAsync(principal,"orders.view"));}
 [Fact]public async Task MenuHidesUnauthorizedLinks(){db.AddRange(new MenuItem{Label="Orders",Url="/orders",Permission="orders.view"},new MenuItem{Label="Secret",Url="/admin/security",Permission="security.manage"},new PermissionGrant{Role="Sales",Permission="orders.view"});await db.SaveChangesAsync();var principal=new ClaimsPrincipal(new ClaimsIdentity(new[]{new Claim(ClaimTypes.NameIdentifier,"staff"),new Claim(ClaimTypes.Role,"Sales")},"Test"));var menu=await new AccessService(db).MenuAsync(principal);Assert.Single(menu);Assert.Equal("Orders",menu[0].Label);}
 [Fact]public async Task GuestCartMergesWithAccount(){var service=new CartService(db);await service.SetAsync("g:test",sku,2);await service.SetAsync("customer",sku,1);await service.MergeAsync("g:test","customer");var row=await db.Set<CartItem>().SingleAsync();Assert.Equal("customer",row.Owner);Assert.Equal(3,row.Quantity);}
 [Fact]public async Task DuplicatePaymentCallbackPostsOnce(){var o=await Checkout();o.PaymentMethod="SSLCommerz";var p=new PaymentTransaction{OrderId=o.Id,TransactionId="trx",Amount=o.Total,Gateway="SSLCommerz"};db.Add(p);await db.SaveChangesAsync();var service=new PaymentService(db,new PaymentGatewayFactory(new[]{new FakeGateway(new VerifiedPayment(true,"trx","BANK001",o.Total,"BDT","0"))}),ledger);await service.VerifyAsync("val",default);await service.VerifyAsync("val",default);Assert.Equal("Paid",o.PaymentStatus);Assert.Equal(1,await db.Set<Journal>().CountAsync());Assert.Equal(1,await db.Set<PaymentCallbackLog>().CountAsync());}
 [Fact]public async Task TransferPreservesInventoryCost(){var parent=await db.Set<Warehouse>().SingleAsync();var target=new Warehouse{Name="Second",BranchId=parent.BranchId};db.Add(target);await db.SaveChangesAsync();await stock.TransferAsync(wh,target.Id,sku,3,"admin");var balance=await db.Set<StockBalance>().SingleAsync(x=>x.WarehouseId==target.Id);Assert.Equal(3,balance.OnHand);Assert.Equal(60m,balance.AverageCost);}
 [Fact]public async Task PaymentMismatchCannotMarkOrderPaid(){var o=await Checkout();var p=new PaymentTransaction{OrderId=o.Id,TransactionId="wrong",Amount=o.Total,Gateway="SSLCommerz"};db.Add(p);await db.SaveChangesAsync();var service=new PaymentService(db,new PaymentGatewayFactory(new[]{new FakeGateway(new VerifiedPayment(true,"wrong","BANK002",1,"BDT","0"))}),ledger);await Assert.ThrowsAsync<BusinessException>(()=>service.VerifyAsync("val",default));Assert.Equal("Unpaid",o.PaymentStatus);Assert.Equal(0,await db.Set<Journal>().CountAsync());}

 [Fact]public async Task PartialReceiptNeverExceedsOrderedQuantity(){var purchase=new PurchaseService(db,stock,ledger);var p=await purchase.CreateAsync(supplier,wh,[sku],[4],[50m],"staff");await purchase.ApproveAsync(p.Id,"staff");var service=new ProcurementService(db,stock,ledger);await service.ReceiveAsync(p.Id,[p.Lines[0].Id],[2],"receipt-1","staff");Assert.Equal("PartReceived",p.Status);Assert.Equal(100m,p.ReceivedTotal);await service.ReceiveAsync(p.Id,[p.Lines[0].Id],[2],"receipt-1","staff");Assert.Equal(12,(await db.Set<StockBalance>().SingleAsync()).OnHand);await Assert.ThrowsAsync<BusinessException>(()=>service.ReceiveAsync(p.Id,[p.Lines[0].Id],[3],"receipt-2","staff"));}
 [Fact]public async Task SupplierReturnReducesStockAndCreatesBalancedJournal(){var purchase=new PurchaseService(db,stock,ledger);var p=await purchase.CreateAsync(supplier,wh,[sku],[4],[50m],"staff");await purchase.ApproveAsync(p.Id,"staff");await purchase.ReceiveAsync(p.Id,"staff");var service=new ProcurementService(db,stock,ledger);await service.ReturnAsync(p.Lines[0].Id,1,"return-1","Damaged","staff");await service.ReturnAsync(p.Lines[0].Id,1,"return-1","Damaged","staff");Assert.Equal(13,(await db.Set<StockBalance>().SingleAsync()).OnHand);Assert.Equal(50m,p.ReturnedTotal);var lines=await db.Set<JournalLine>().ToListAsync();Assert.Equal(lines.Sum(x=>x.Debit),lines.Sum(x=>x.Credit));}
 [Fact]public async Task RequisitionQuotationAwardCreatesPurchase(){var service=new ProcurementService(db,stock,ledger);var id=await service.RequestAsync(wh,"Replenish",[sku],[3],"staff");await service.ApproveAsync(id,"manager");var r=await db.Set<PurchaseRequisition>().Include(x=>x.Lines).SingleAsync();await service.QuoteAsync(id,supplier,DateTime.UtcNow.AddDays(2),"quote-ref",[r.Lines[0].Id],[45m],"staff");var quote=await db.Set<SupplierQuotation>().SingleAsync();var po=await service.AwardAsync(quote.Id,"manager");Assert.Equal(135m,(await db.Set<PurchaseOrder>().SingleAsync(x=>x.Id==po)).Total);await Assert.ThrowsAsync<BusinessException>(()=>service.AwardAsync(quote.Id,"manager"));}
 [Fact]public async Task ActiveCampaignChangesServerCheckoutPrice(){var skuRow=await db.Set<ProductSku>().SingleAsync();db.Add(new Campaign{Name="Flash",ProductId=skuRow.ProductId,Percent=20,StartsAt=DateTime.UtcNow.AddDays(-1),EndsAt=DateTime.UtcNow.AddDays(1)});await db.SaveChangesAsync();var o=await Checkout();Assert.Equal(170m,o.Total);}
 [Fact]public async Task ClosedAccountingPeriodRejectsPosting(){db.Add(new AccountingPeriod{Name="Closed",StartsAt=DateTime.UtcNow.AddDays(-1),EndsAt=DateTime.UtcNow.AddDays(1),Closed=true});await db.SaveChangesAsync();await Assert.ThrowsAsync<BusinessException>(()=>ledger.PostAsync("test","Closed period",("1000",10m,0m,""),("1100",0m,10m,"")));}
 [Fact]public async Task StoreCreditRedeemsWithoutCashCollection(){db.Add(new AccountHead{Code="2200",Name="Store credit",Type="Liability"});db.Add(new StoreCredit{UserId="customer",Amount=500,Reason="Test opening credit"});await db.SaveChangesAsync();await new CartService(db).SetAsync("customer",sku,2);var request=Request(Guid.NewGuid().ToString()) with {Method="StoreCredit"};var order=await orders.CheckoutAsync(request);Assert.Equal("Paid",order.PaymentStatus);Assert.Equal(290m,await new StoreCreditService(db,ledger).BalanceAsync("customer"));}
 [Fact]public async Task BankMatchRejectsDifferentAmount(){await ledger.PostAsync("voucher","Receipt",("1000",100m,0m,""),("1100",0m,100m,""));await db.SaveChangesAsync();var line=await db.Set<JournalLine>().SingleAsync(x=>x.Debit==100);await Assert.ThrowsAsync<BusinessException>(()=>new ReconciliationService(db,ledger).BankAsync("statement",DateTime.UtcNow,99,line.Id,"staff"));}

 [Fact]public async Task OnlineRefundRequiresVerifiedStatusBeforeAccounting(){var o=await Checkout();db.Add(new PaymentTransaction{OrderId=o.Id,TransactionId="refund-trx",Gateway="SSLCommerz",Amount=o.Total,Status="Paid",GatewayTransactionId="bank-ref"});var refund=new PaymentRefund{OrderId=o.Id,Amount=10,Reason="Approved return"};db.Add(refund);await db.SaveChangesAsync();var configuration=new Microsoft.Extensions.Configuration.ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{["Payments:SSLCommerz:RefundEnabled"]="true",["Payments:SSLCommerz:Sandbox"]="true",["Payments:SSLCommerz:StoreId"]="test-only",["Payments:SSLCommerz:StorePassword"]="test-only"}).Build();var service=new RefundGatewayService(new HttpClient(new RefundHandler()),db,configuration,new ReturnService(db,stock,ledger),ledger);await service.StartAsync(refund.Id,"admin",default);Assert.Equal("Processing",refund.Status);Assert.Equal(0,await db.Set<Journal>().CountAsync());await service.QueryAsync(refund.Id,"admin",default);await service.QueryAsync(refund.Id,"admin",default);Assert.Equal("Completed",refund.Status);Assert.Equal(1,await db.Set<Journal>().CountAsync());await Assert.ThrowsAsync<BusinessException>(()=>service.StartAsync(refund.Id,"admin",default));}

 [Fact]public async Task ReplacementConsumesRefundOnceAndReservesStock(){var o=await Checkout(1);foreach(var next in new[]{OrderStatus.Confirmed,OrderStatus.Processing,OrderStatus.Packed,OrderStatus.ReadyToShip,OrderStatus.Shipped,OrderStatus.OutForDelivery,OrderStatus.Delivered})await orders.TransitionAsync(o.Id,next,"staff");await orders.CollectCodAsync(o.Id,"staff");var service=new ReturnService(db,stock,ledger);await service.RequestAsync(o.Lines[0].Id,1,"Faulty item","customer");var request=await db.Set<ReturnRequest>().SingleAsync();await service.InspectAsync(request.Id,true,true,"Inspected","staff");var replacements=new ReplacementService(db,stock,ledger);var id=await replacements.CreateAsync(request.Id,"staff");Assert.Equal(id,await replacements.CreateAsync(request.Id,"staff"));Assert.Equal(1,(await db.Set<StockBalance>().SingleAsync()).Reserved);Assert.Equal("ReplacementIssued",(await db.Set<PaymentRefund>().SingleAsync()).Status);await Assert.ThrowsAsync<BusinessException>(async()=>await service.RecordRefundAsync((await db.Set<PaymentRefund>().SingleAsync()).Id,"double","staff"));var lines=await db.Set<JournalLine>().ToListAsync();Assert.Equal(lines.Sum(x=>x.Debit),lines.Sum(x=>x.Credit));}
 [Fact]public async Task UserMenuDenyCannotGrantControllerPermission(){var menu=new MenuItem{Label="Orders",Url="/orders",Permission="orders.view"};db.AddRange(menu,new PermissionGrant{Role="Sales",Permission="orders.view"},new UserMenuPermission{UserId="staff",MenuItemId=menu.Id,Allowed=false});await db.SaveChangesAsync();var principal=new ClaimsPrincipal(new ClaimsIdentity(new[]{new Claim(ClaimTypes.NameIdentifier,"staff"),new Claim(ClaimTypes.Role,"Sales")},"Test"));var service=new AccessService(db);Assert.Empty(await service.MenuAsync(principal));Assert.True(await service.HasAsync(principal,"orders.view"));Assert.False(await service.HasAsync(principal,"security.manage"));}
 [Fact]public async Task TerminalReferenceCannotBeReused(){var first=await Checkout(1);first.Source="POS";await db.SaveChangesAsync();await orders.CollectTerminalAsync(first.Id,"Card","terminal-proof","staff");Assert.Equal("Paid",first.PaymentStatus);var second=await Checkout(1);second.Source="POS";await db.SaveChangesAsync();await Assert.ThrowsAsync<BusinessException>(()=>orders.CollectTerminalAsync(second.Id,"MFS","terminal-proof","staff"));}
 [Fact]public async Task ReportFiltersApplyBeforePagination(){var order=await Checkout(1);var filters=new Ecommerce.Web.ReportFilters{CustomerId="customer",ProductId=(await db.Set<ProductSku>().SingleAsync()).ProductId};var query=filters.Apply(db.Set<OrderLine>(),typeof(OrderLine));Assert.Single(await query.ToListAsync());filters.CustomerId="other";Assert.Empty(await filters.Apply(db.Set<OrderLine>(),typeof(OrderLine)).ToListAsync());Assert.Throws<BusinessException>(()=>new Ecommerce.Web.ReportFilters{SupplierId=Guid.NewGuid()}.Apply(db.Set<Product>(),typeof(Product)));}
 [Fact]public async Task RecommendationUsesViewedCategory(){var product=await db.Set<Product>().SingleAsync();db.Add(new ProductView{UserId="customer",ProductId=product.Id});await db.SaveChangesAsync();Assert.Equal(product.Id,(await new RecommendationService(db).ForAsync("customer")).First().Id);}
 [Fact]public async Task ActorFieldsAreStamped(){db.CurrentActor="staff-actor";var c=new Category{Name="New",Slug="new"};db.Add(c);await db.SaveChangesAsync();Assert.Equal("staff-actor",c.CreatedBy);db.CurrentActor="editor";c.Name="Updated";await db.SaveChangesAsync();Assert.Equal("editor",c.UpdatedBy);}

 [Fact]public async Task CampaignCapAndQuotaAreAppliedAtCheckout(){var c=new Campaign{Name="Limited",Percent=50,MaximumDiscount=30,MinimumPurchase=150,UsageLimit=1,PerCustomerLimit=1};db.Add(c);await db.SaveChangesAsync();var first=await Checkout(2);Assert.Equal(180,first.Total);var use=await db.Set<CampaignUse>().SingleAsync();Assert.Equal(30,use.Discount);var second=await Checkout(2);Assert.Equal(210,second.Total);Assert.Equal(1,await db.Set<CampaignUse>().CountAsync());}
 [Fact]public async Task CampaignMinimumAndPerCustomerLimitAreIndependent(){db.Add(new Campaign{Name="Customer limit",Percent=10,MinimumPurchase=200,UsageLimit=10,PerCustomerLimit=1});await db.SaveChangesAsync();Assert.Equal(110,(await Checkout(1)).Total);Assert.Equal(190,(await Checkout(2)).Total);Assert.Equal(210,(await Checkout(2)).Total);await new CartService(db).SetAsync("second-customer",sku,2);var other=await orders.CheckoutAsync(Request(Guid.NewGuid().ToString()) with {UserId="second-customer"});Assert.Equal(190,other.Total);}
 [Fact]public async Task SplitFulfilmentIssuesAndReturnsAcrossLocations(){var parent=await db.Set<Warehouse>().SingleAsync();var second=new Warehouse{Name="Second",BranchId=parent.BranchId};db.Add(second);await db.SaveChangesAsync();await stock.TransferAsync(wh,second.Id,sku,6,"staff");var o=await Checkout(7);Assert.Equal(2,await db.Set<OrderAllocation>().CountAsync());foreach(var next in new[]{OrderStatus.Confirmed,OrderStatus.Processing,OrderStatus.Packed,OrderStatus.ReadyToShip,OrderStatus.Shipped,OrderStatus.OutForDelivery,OrderStatus.Delivered})await orders.TransitionAsync(o.Id,next,"staff");Assert.Equal(3,await db.Set<StockBalance>().SumAsync(x=>x.OnHand));await orders.CollectCodAsync(o.Id,"staff");var returns=new ReturnService(db,stock,ledger);await returns.RequestAsync(o.Lines[0].Id,7,"Return all","customer");await returns.InspectAsync((await db.Set<ReturnRequest>().SingleAsync()).Id,true,true,"Inspected","staff");Assert.Equal(10,await db.Set<StockBalance>().SumAsync(x=>x.OnHand));Assert.Equal(OrderStatus.Returned,o.Status);await returns.RecordRefundAsync((await db.Set<PaymentRefund>().SingleAsync()).Id,"cash-refund","staff");Assert.Equal(OrderStatus.Refunded,o.Status);Assert.Equal(7,await db.Set<OrderAllocation>().SumAsync(x=>x.RestockedQuantity));}
 [Fact]public async Task SplitCancellationReleasesAllReservations(){var first=await db.Set<Warehouse>().SingleAsync();var second=new Warehouse{Name="Other",BranchId=first.BranchId};db.Add(second);await db.SaveChangesAsync();await stock.TransferAsync(wh,second.Id,sku,6,"staff");var o=await Checkout(7);await orders.TransitionAsync(o.Id,OrderStatus.Cancelled,"staff");Assert.Equal(0,await db.Set<StockBalance>().SumAsync(x=>x.Reserved));Assert.Equal(10,await db.Set<StockBalance>().SumAsync(x=>x.OnHand));}
 [Fact]public async Task PosCannotReserveAnotherStoresStock(){var first=await db.Set<Warehouse>().SingleAsync();var second=new Warehouse{Name="Other",BranchId=first.BranchId};db.Add(second);await db.SaveChangesAsync();await stock.TransferAsync(wh,second.Id,sku,9,"staff");await new CartService(db).SetAsync("customer",sku,2);await Assert.ThrowsAsync<BusinessException>(()=>orders.CheckoutAsync(Request(Guid.NewGuid().ToString()) with {Source="POS"}));}
 [Fact]public async Task StoreCreatesIndependentBalanceAndSupportsOpeningStock(){var branch=(await db.Set<Warehouse>().SingleAsync()).BranchId;var id=await new StoreInventoryService(db,ledger).CreateAsync("Outlet",branch,"staff");var store=await db.Set<Store>().SingleAsync(x=>x.Id==id);Assert.NotEqual(wh,store.WarehouseId);await stock.AdjustAsync(store.WarehouseId,sku,3,"Opening","staff");Assert.Equal(3,(await db.Set<StockBalance>().SingleAsync(x=>x.WarehouseId==store.WarehouseId)).OnHand);Assert.Equal(10,(await db.Set<StockBalance>().SingleAsync(x=>x.WarehouseId==wh)).OnHand);}
 [Fact]public async Task SupplierInvoiceMatchesReceiptsAndGatesPayment(){var purchases=new PurchaseService(db,stock,ledger);var p=await purchases.CreateAsync(supplier,wh,[sku],[4],[50m],"staff");await purchases.ApproveAsync(p.Id,"staff");await purchases.ReceiveAsync(p.Id,"staff");var invoices=new SupplierInvoiceService(db,ledger);await Assert.ThrowsAsync<BusinessException>(()=>purchases.PayAsync(p.Id,50,"staff"));var id=await invoices.CreateAsync(p.Id,"INV-1",DateTime.UtcNow,DateTime.UtcNow.AddDays(30),[p.Lines[0].Id],[2],"staff");await Assert.ThrowsAsync<BusinessException>(()=>purchases.PayAsync(p.Id,50,"staff"));await invoices.ApproveAsync(id,"manager");await invoices.ApproveAsync(id,"manager");Assert.Equal(1,await db.Set<Journal>().CountAsync());await purchases.PayAsync(p.Id,100,"staff");await Assert.ThrowsAsync<BusinessException>(()=>purchases.PayAsync(p.Id,1,"staff"));await Assert.ThrowsAsync<BusinessException>(()=>invoices.CreateAsync(p.Id,"INV-2",DateTime.UtcNow,DateTime.UtcNow,[p.Lines[0].Id],[3],"staff"));await Assert.ThrowsAsync<BusinessException>(()=>invoices.CreateAsync(p.Id,"INV-1",DateTime.UtcNow,DateTime.UtcNow,[p.Lines[0].Id],[1],"staff"));}
 async Task<ReturnRequest> PaidReturn(){var o=await Checkout(1);foreach(var next in new[]{OrderStatus.Confirmed,OrderStatus.Processing,OrderStatus.Packed,OrderStatus.ReadyToShip,OrderStatus.Shipped,OrderStatus.OutForDelivery,OrderStatus.Delivered})await orders.TransitionAsync(o.Id,next,"staff");await orders.CollectCodAsync(o.Id,"staff");var returns=new ReturnService(db,stock,ledger);await returns.RequestAsync(o.Lines[0].Id,1,"Exchange","customer");var r=await db.Set<ReturnRequest>().SingleAsync();await returns.InspectAsync(r.Id,true,true,"Good condition","staff");return r;}
 [Fact]public async Task CheaperSkuExchangePreservesResidualCredit(){db.Add(new AccountHead{Code="2200",Name="Store credit",Type="Liability"});var original=await db.Set<ProductSku>().SingleAsync();var replacement=new ProductSku{ProductId=original.ProductId,Name="Other",SKU="OTHER",SalePrice=80,PurchasePrice=40};db.AddRange(replacement,new StockBalance{WarehouseId=wh,SkuId=replacement.Id,OnHand=3,AverageCost=40});await db.SaveChangesAsync();var r=await PaidReturn();var id=await new ReplacementService(db,stock,ledger).CreateAsync(r.Id,"staff",replacement.Id,1);var o=await db.Set<Order>().Include(x=>x.Lines).SingleAsync(x=>x.Id==id);Assert.Equal(80,o.Total);Assert.Equal(replacement.Id,o.Lines.Single().SkuId);Assert.Equal(20,await new StoreCreditService(db,ledger).BalanceAsync("customer"));Assert.Equal(80,(await db.Set<PaymentTransaction>().SingleAsync(x=>x.OrderId==id)).Amount);var lines=await db.Set<JournalLine>().ToListAsync();Assert.Equal(lines.Sum(x=>x.Debit),lines.Sum(x=>x.Credit));}
 [Fact]public async Task ExpensiveExchangeRequiresExactVerifiedCashDifference(){var original=await db.Set<ProductSku>().SingleAsync();var target=new ProductSku{ProductId=original.ProductId,Name="Upgrade",SKU="UPGRADE",SalePrice=140};db.AddRange(target,new StockBalance{WarehouseId=wh,SkuId=target.Id,OnHand=2,AverageCost=60});await db.SaveChangesAsync();var r=await PaidReturn();var service=new ReplacementService(db,stock,ledger);await Assert.ThrowsAsync<BusinessException>(()=>service.CreateAsync(r.Id,"staff",target.Id,1));db.ChangeTracker.Clear();var id=await service.CreateAsync(r.Id,"staff",target.Id,1,40,"receipt-upgrade");Assert.Equal(140,(await db.Set<Order>().SingleAsync(x=>x.Id==id)).Total);Assert.Equal(40,(await db.Set<JournalLine>().Include(x=>x.Journal).SingleAsync(x=>x.Journal.Reference=="EXCHANGE-CASH-"+id&&x.Debit>0)).Debit);}
 [Fact]public async Task AiCustomerContextDoesNotExposeAdminOrOtherOrders(){var own=await Checkout(1);await new CartService(db).SetAsync("another-user",sku,1);var secret=await orders.CheckoutAsync(Request(Guid.NewGuid().ToString()) with {UserId="another-user"});var handler=new CaptureAiHandler();var configuration=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{["Ollama:Model"]="test"}).Build();var ai=new OllamaService(new HttpClient(handler){BaseAddress=new Uri("http://localhost/")},db,configuration);await ai.AskAsync("Test Product", "customer",false,default);Assert.Contains(own.Number,handler.Payload);Assert.DoesNotContain(secret.Number,handler.Payload);Assert.DoesNotContain("DeliveredSalesThisMonth",handler.Payload);await ai.AskAsync("monthly sales top products", "customer",true,default);Assert.Contains("DeliveredSalesThisMonth",handler.Payload);Assert.Contains("PendingDelivery",handler.Payload);}
 [Fact]public async Task CodCollectedAfterReturnUsesRemainingReceivable(){var o=await Checkout(2);foreach(var next in new[]{OrderStatus.Confirmed,OrderStatus.Processing,OrderStatus.Packed,OrderStatus.ReadyToShip,OrderStatus.Shipped,OrderStatus.OutForDelivery,OrderStatus.Delivered})await orders.TransitionAsync(o.Id,next,"staff");var service=new ReturnService(db,stock,ledger);await service.RequestAsync(o.Lines[0].Id,1,"Return before cash","customer");await service.InspectAsync((await db.Set<ReturnRequest>().SingleAsync()).Id,true,true,"Inspected","staff");Assert.Equal(110,await orders.CodDueAsync(o));await Assert.ThrowsAsync<BusinessException>(()=>orders.CollectCodAsync(o.Id,"staff",210));await orders.CollectCodAsync(o.Id,"staff",110);Assert.Equal(110,(await db.Set<PaymentTransaction>().SingleAsync()).Amount);var lines=await db.Set<JournalLine>().Include(x=>x.AccountHead).Where(x=>x.AccountHead.Code=="1100").ToListAsync();Assert.Equal(0,lines.Sum(x=>x.Debit-x.Credit));}
 [Fact]public async Task CloudAiUsesAuthorizedContextAndDoesNotLeakOtherOrders(){
 var own=await Checkout(1);await new CartService(db).SetAsync("another-user",sku,1);var secret=await orders.CheckoutAsync(Request(Guid.NewGuid().ToString()) with {UserId="another-user"});
 var handler=new CaptureAiHandler();var configuration=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{["Ollama:Cloud:Enabled"]="true",["Ollama:Cloud:ApiKey"]="test-secret",["Ollama:Cloud:Model"]="test"}).Build();
 using var localClient=new HttpClient(new CaptureAiHandler()){BaseAddress=new Uri("http://localhost/")};
 var ai=new OllamaService(localClient,db,configuration,new FakeCloudFactory(handler));await ai.AskAsync("Test Product","customer",false,default);
 Assert.Contains(own.Number,handler.Payload);Assert.DoesNotContain(secret.Number,handler.Payload);Assert.DoesNotContain("DeliveredSalesThisMonth",handler.Payload);Assert.DoesNotContain("test-secret",handler.Payload);
 }
 sealed class FakeCloudFactory(HttpMessageHandler handler):IHttpClientFactory {public HttpClient CreateClient(string name)=>new(handler,false);}
 sealed class CaptureAiHandler:HttpMessageHandler{public string Payload="";protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct){Payload=await request.Content!.ReadAsStringAsync(ct);return new HttpResponseMessage(System.Net.HttpStatusCode.OK){Content=new StringContent("{\"message\":{\"content\":\"Authorized facts\"}}")};}}
 sealed class RefundHandler:HttpMessageHandler {protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct){var status=request.RequestUri!.Query.Contains("refund_ref_id=")?"refunded":"success";var json=System.Text.Json.JsonSerializer.Serialize(new{APIConnect="DONE",bank_tran_id="bank-ref",trans_id="refund-trx",tran_id="refund-trx",refund_ref_id="gateway-refund-1",status});return Task.FromResult(new HttpResponseMessage(System.Net.HttpStatusCode.OK){Content=new StringContent(json)});}}
 sealed class FakeGateway(VerifiedPayment result):IPaymentGateway {public string Name=>"SSLCommerz";public Task<VerifiedPayment> VerifyAsync(string id,CancellationToken ct)=>Task.FromResult(result);public Task<GatewaySession> CreateAsync(Order o,PaymentTransaction p,CancellationToken ct)=>Task.FromResult(new GatewaySession("https://example.com",p.TransactionId));}
}
