using System.ComponentModel.DataAnnotations;
namespace Ecommerce.Domain;
public class PurchaseRequisition:Entity {public string Number {get;set;}="";public Guid WarehouseId {get;set;}public Warehouse Warehouse {get;set;}=null!;public string RequestedBy {get;set;}="";public string Purpose {get;set;}="";public string Status {get;set;}="Draft";public List<RequisitionLine> Lines {get;set;}=[];}
public class RequisitionLine:Entity {public Guid PurchaseRequisitionId {get;set;}public PurchaseRequisition PurchaseRequisition {get;set;}=null!;public Guid SkuId {get;set;}public ProductSku Sku {get;set;}=null!;public int Quantity {get;set;}}
public class SupplierQuotation:Entity {public Guid PurchaseRequisitionId {get;set;}public PurchaseRequisition PurchaseRequisition {get;set;}=null!;public Guid SupplierId {get;set;}public Supplier Supplier {get;set;}=null!;public DateTime ValidUntil {get;set;}public string Reference {get;set;}="";public string Status {get;set;}="Submitted";public decimal Total {get;set;}public List<QuotationLine> Lines {get;set;}=[];}
public class QuotationLine:Entity {public Guid SupplierQuotationId {get;set;}public SupplierQuotation SupplierQuotation {get;set;}=null!;public Guid SkuId {get;set;}public ProductSku Sku {get;set;}=null!;public int Quantity {get;set;}public decimal UnitCost {get;set;}}
public class GoodsReceipt:Entity {public Guid PurchaseOrderId {get;set;}public PurchaseOrder PurchaseOrder {get;set;}=null!;public string Reference {get;set;}="";public string ActorId {get;set;}="";public List<GoodsReceiptLine> Lines {get;set;}=[];}
public class GoodsReceiptLine:Entity {public Guid GoodsReceiptId {get;set;}public GoodsReceipt GoodsReceipt {get;set;}=null!;public Guid PurchaseLineId {get;set;}public PurchaseLine PurchaseLine {get;set;}=null!;public int Quantity {get;set;}public decimal UnitCost {get;set;}}
public class SupplierReturn:Entity {public Guid PurchaseLineId {get;set;}public PurchaseLine PurchaseLine {get;set;}=null!;public string Reference {get;set;}="";public string Reason {get;set;}="";public int Quantity {get;set;}public decimal Amount {get;set;}public string ActorId {get;set;}="";}
public class Campaign:NamedEntity {[Range(0,999999999)]public decimal MinimumPurchase {get;set;} [Range(0,999999999)]public decimal MaximumDiscount {get;set;}=999999999; [Range(1,int.MaxValue)]public int UsageLimit {get;set;}=int.MaxValue; [Range(1,int.MaxValue)]public int PerCustomerLimit {get;set;}=int.MaxValue;public Guid? ProductId {get;set;}public Product? Product {get;set;}public Guid? CategoryId {get;set;}public Category? Category {get;set;}public string CustomerId {get;set;}="";[Range(0,100)]public decimal Percent {get;set;}public DateTime StartsAt {get;set;}=DateTime.UtcNow;public DateTime EndsAt {get;set;}=DateTime.UtcNow.AddDays(7);}
public class Banner:NamedEntity {public string ImagePath {get;set;}="/images/fallback.svg";public string Link {get;set;}="/products";public string Subtitle {get;set;}="";public int SortOrder {get;set;}public DateTime StartsAt {get;set;}=DateTime.UtcNow;public DateTime EndsAt {get;set;}=DateTime.UtcNow.AddYears(1);}
public class ProductAttribute:NamedEntity {}
public class AttributeValue:NamedEntity {public Guid ProductAttributeId {get;set;}public ProductAttribute ProductAttribute {get;set;}=null!;}
public class VariantAttribute:Entity {public Guid ProductSkuId {get;set;}public ProductSku ProductSku {get;set;}=null!;public Guid AttributeValueId {get;set;}public AttributeValue AttributeValue {get;set;}=null!;}
public class ContentPage:NamedEntity {[Required]public string Slug {get;set;}="";[Required]public string Body {get;set;}="";public string MetaDescription {get;set;}="";}
public class AccountingPeriod:NamedEntity {public DateTime StartsAt {get;set;}public DateTime EndsAt {get;set;}public bool Closed {get;set;}}
public class BankStatementLine:Entity {public string Reference {get;set;}="";public DateTime Date {get;set;}=DateTime.UtcNow;public decimal Amount {get;set;}public Guid? JournalLineId {get;set;}public JournalLine? JournalLine {get;set;}public string Status {get;set;}="Unmatched";}
public class PaymentReconciliation:Entity {public Guid PaymentTransactionId {get;set;}public PaymentTransaction PaymentTransaction {get;set;}=null!;public decimal ExternalAmount {get;set;}public string ExternalReference {get;set;}="";public string Status {get;set;}="";public string ActorId {get;set;}="";}
public class SupportReply:Entity {public Guid SupportTicketId {get;set;}public SupportTicket SupportTicket {get;set;}=null!;public string AuthorId {get;set;}="";public bool Staff {get;set;}public string Message {get;set;}="";}
public class OutboxMessage:Entity {public string UserId {get;set;}="";public string Message {get;set;}="";public string Status {get;set;}="Pending";public int Attempts {get;set;}public DateTime NextAttemptAt {get;set;}=DateTime.UtcNow;}
public class StoreCredit:Entity {public string UserId {get;set;}="";public Guid? PaymentRefundId {get;set;}public PaymentRefund? PaymentRefund {get;set;}public Guid? OrderId {get;set;}public Order? Order {get;set;}public decimal Amount {get;set;}public string Reason {get;set;}="";}

public class ProductView:Entity {public string UserId {get;set;}="";public Guid ProductId {get;set;}public Product Product {get;set;}=null!;}
public class Replacement:Entity {public Guid ReturnRequestId {get;set;}public ReturnRequest ReturnRequest {get;set;}=null!;public Guid OrderId {get;set;}public Order Order {get;set;}=null!;public string ActorId {get;set;}="";}
public class Menu:NamedEntity {public int SortOrder {get;set;}}
public class RoleMenuPermission:Entity {public string Role {get;set;}="";public Guid MenuItemId {get;set;}public MenuItem MenuItem {get;set;}=null!;public bool Allowed {get;set;}=true;}
public class UserMenuPermission:Entity {public string UserId {get;set;}="";public Guid MenuItemId {get;set;}public MenuItem MenuItem {get;set;}=null!;public bool Allowed {get;set;}=true;}
public class DeliveryHistory:Entity {public Guid DeliveryId {get;set;}public Delivery Delivery {get;set;}=null!;public string Status {get;set;}="";public string Note {get;set;}="";public string ActorId {get;set;}="";}

public class DeliveryMethod:NamedEntity {public string Description {get;set;}="";}
public class District:NamedEntity {}
public class DeliveryArea:NamedEntity {public Guid DistrictId {get;set;}public District District {get;set;}=null!;}
public class PaymentGateway:NamedEntity {public string ProviderCode {get;set;}="";public string Description {get;set;}="";public bool Sandbox {get;set;}=true;}

public class CampaignUse:Entity {public Guid CampaignId {get;set;}public Campaign Campaign {get;set;}=null!;public Guid OrderId {get;set;}public Order Order {get;set;}=null!;public string UserId {get;set;}="";public decimal Discount {get;set;}}
public class OrderAllocation:Entity {public Guid OrderLineId {get;set;}public OrderLine OrderLine {get;set;}=null!;public Guid WarehouseId {get;set;}public Warehouse Warehouse {get;set;}=null!;public int Quantity {get;set;}public int RestockedQuantity {get;set;}public decimal UnitCost {get;set;}}
public class SupplierInvoice:Entity {public Guid PurchaseOrderId {get;set;}public PurchaseOrder PurchaseOrder {get;set;}=null!;public Guid SupplierId {get;set;}public Supplier Supplier {get;set;}=null!;[Required,MaxLength(100)]public string Number {get;set;}="";public DateTime InvoiceDate {get;set;}=DateTime.UtcNow;public DateTime DueDate {get;set;}=DateTime.UtcNow;public decimal Total {get;set;}public string Status {get;set;}="Draft";public List<SupplierInvoiceLine> Lines {get;set;}=[];}
public class SupplierInvoiceLine:Entity {public Guid SupplierInvoiceId {get;set;}public SupplierInvoice SupplierInvoice {get;set;}=null!;public Guid PurchaseLineId {get;set;}public PurchaseLine PurchaseLine {get;set;}=null!;public int Quantity {get;set;}public decimal UnitCost {get;set;}}
